import { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

// comp
import { Box } from "@mui/material";
import { Videos, ChannelCard } from "../../components";

// utils
import { fetchFromAPI } from "@/utils/fetchFromAPI";

// interfaces
import { Video, VideosSchema } from "@/typings";

export default function ChannelDetails() {
  const [channelDetail, setChannelDetail] = useState<Video>();
  const [videos, setVideos] = useState<Video[]>([]);

  const {
    query: { channelId },
  } = useRouter();

  useEffect(() => {
    fetchFromAPI(`channels?part=snippet&id=${channelId}`).then((data) =>
      setChannelDetail(data?.items[0])
    );

    fetchFromAPI(`search?channelId=${channelId}&part=snippet&order=date`).then(
      (data: VideosSchema) => setVideos(data?.items)
    );
  }, [channelId]);

  return (
    <div>
      <Head>
        <title>Youtube-Clone | {channelId}</title>
        <meta name="description" content="Generated by create @nkjy" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box minHeight="95vh">
        <div
          style={{
            background:
              "linear-gradient(90deg, rgba(0,238,247,1) 0%, rgba(206,3,184,1) 100%, rgba(0,212,255,1) 100%)",
            zIndex: 10,
            height: "300px",
          }}
        />
        <ChannelCard channelDetail={channelDetail} mt="-110px" />
      </Box>

      <Box display="flex" p="2">
        <Box sx={{ mr: { sm: "100px" } }} />
        <Videos videos={videos} />
      </Box>
    </div>
  );
}
