import Head from "next/head";
import React, { useState, useEffect } from "react";

// comp
import { Typography } from "@mui/material";
import { Videos } from "@/components";

// utils
import { fetchFromAPI } from "@/utils/fetchFromAPI";

// interfaces
import { Video, VideosSchema } from "@/typings";
import { useRouter } from "next/router";

export default function SearchFeed() {
  const [videos, setVideos] = useState<Video[]>([]);
  const {
    query: { searchTerm },
  } = useRouter();

  useEffect(() => {
    fetchFromAPI(`search?part=snippet&q=${searchTerm}`)
      .then((videos: VideosSchema) => setVideos(videos.items))
      .catch((err) => alert(err.message));
  }, [searchTerm]);

  return (
    <>
      <Head>
        <title>Youtube-Clone | Search</title>
        <meta name="description" content="Generated by create @nkjy" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h4" fontWeight="bold" mb={2} sx={{ color: "white" }}>
        Search Results for:{" "}
        <span style={{ color: "#F31503" }}>{searchTerm}</span> videos
      </Typography>
      <Videos videos={videos} />
    </>
  );
}
