import Head from "next/head";
import React, { useState, useEffect } from "react";
import axios from "axios";

// comp
import { Box, Stack, Typography } from "@mui/material";
import { SideBar, Videos } from "@/components";
import { fetchFromAPI } from "@/utils/fetchFromAPI";

type Video = {
  id: {
    videoId: string;
    channelId: string;
  };
};

export default function Home() {
  const [selectedCategory, setSelectedCategory] = useState("New");
  const [videos, setVideos] = useState<Video[]>([]);

  useEffect(() => {
    fetchFromAPI(`search?part=snippet&q=${selectedCategory}`)
      .then((videos) => setVideos(videos))
      .catch((err) => alert(err.message));
  }, [selectedCategory]);

  return (
    <>
      <Head>
        <title>Youtube-Clone | Home</title>
        <meta name="description" content="Generated by create @nkjy" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack sx={{ flexDirection: { sx: "column", md: "row" } }}>
        <Box
          sx={{
            height: { sx: "auto", md: "92vh" },
            borderRight: "1px solid #3d3d3d",
            px: { sx: 0, md: 2 },
          }}
        >
          <SideBar
            selectedCategory={selectedCategory}
            setSelectedCategory={setSelectedCategory}
          />
          <Typography
            className="copyright"
            variant="body2"
            sx={{ mt: 1.5, color: "#fff" }}
          >
            Copyright 2023 @NKJY
          </Typography>
        </Box>

        <Box p={2} sx={{ overflowY: "auto", height: "90vh", flex: 2 }}>
          <Typography
            fontWeight="bold"
            mb={2}
            variant="h4"
            sx={{ color: "#fff" }}
          >
            {selectedCategory} Videos
          </Typography>

          <Videos videos={videos} />
        </Box>
      </Stack>
    </>
  );
}
